// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsnRtdjO7xlpEMCY6pJtm9wwZ9AoiRv4',
    appId: '1:89866803360:web:bcba785767c8d197a1d1c5',
    messagingSenderId: '89866803360',
    projectId: 'onechatgdp',
    authDomain: 'onechatgdp.firebaseapp.com',
    storageBucket: 'onechatgdp.appspot.com',
    measurementId: 'G-D2J7CTCKDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2yYRaE-JEsExwCNh7o2-EI64yBeGuXps',
    appId: '1:89866803360:android:4782c05220b6ea94a1d1c5',
    messagingSenderId: '89866803360',
    projectId: 'onechatgdp',
    storageBucket: 'onechatgdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXaAFbN_TieAzLWsqvCyL_QwfWGXJSi8',
    appId: '1:89866803360:ios:1b41ee8251030955a1d1c5',
    messagingSenderId: '89866803360',
    projectId: 'onechatgdp',
    storageBucket: 'onechatgdp.appspot.com',
    iosClientId:
        '89866803360-jie57uh4gl6fl90tcqkcha1j8ihql7ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneChatgptFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRXaAFbN_TieAzLWsqvCyL_QwfWGXJSi8',
    appId: '1:89866803360:ios:66e825cab9971c35a1d1c5',
    messagingSenderId: '89866803360',
    projectId: 'onechatgdp',
    storageBucket: 'onechatgdp.appspot.com',
    iosClientId:
        '89866803360-tt0e5rlluj3h2828uadt38krcgajov72.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneChatgptFlutter.RunnerTests',
  );
}
