name: Build and Alpha APK

on:
  push:
    branches:
      - alpha
  pull_request:
    branches:
      - alpha
    types: [closed]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: ["armeabi-v7a", "arm64-v8a", "x86_64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Decode keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/android/app/keystore.jks
        shell: bash

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
        env:
          KEYALIAS: ${{ secrets.KEYALIAS }}
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
          STOREPASSWORD: ${{ secrets.STOREPASSWORD }}

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-${{ matrix.abi }}-release.apk build/app/outputs/flutter-apk/OneChatGPT-${{ matrix.abi }}.apk

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OneChatGPT-${{ matrix.abi }}.apk
          path: build/app/outputs/flutter-apk/OneChatGPT-${{ matrix.abi }}.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK from Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.apk"
          tag: Alpha
          name: OneChatGPT Alpha
          body:  |
            cat > release.txt << 'EOF'
            ## 我应该下载哪个版本？

            ### fat APK
            - 如果你不能分辨设备： OneChatGPT.apk（其中包含为所有目标 ABI 编译的代码。此类 APK 的大小比拆分的 APK 大，导致用户下载不适用于其设备架构的本机二进制文件）

            ### APKs
            - ARM 64位: arm64-v8a.apk（支持 64 位指令的现代 Android 设备）
            - ARM 32位: armeabi-v7a.apk（用于较旧的 Android 设备）
            - x86_64: x86_64.apk（用于 Android 模拟器和一些基于 x86 的 Android 设备）

            更新时间：  ${{ env.BUILDTIME }}.
            EOF
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
